"""Nifty 100 constituents list.

Updated periodically. Source: NSE India index constituents.
Last updated: 2026-05-06
"""

NIFTY_100 = [
    "ADANIENT", "ADANIGREEN", "ADANIPORTS", "AMBUJACEM", "APOLLOHOSP",
    "ASIANPAINT", "ATGL", "AXISBANK", "BAJAJ-AUTO", "BAJAJFINSV",
    "BAJFINANCE", "BANKBARODA", "BEL", "BHARTIARTL", "BHEL",
    "BOSCHLTD", "BPCL", "BRITANNIA", "CANBK", "CHOLAFIN",
    "CIPLA", "COALINDIA", "COLPAL", "DLF", "DIVISLAB",
    "DRREDDY", "EICHERMOT", "GAIL", "GODREJCP", "GRASIM",
    "HAL", "HAVELLS", "HCLTECH", "HDFCBANK", "HDFCLIFE",
    "HEROMOTOCO", "HINDALCO", "HINDUNILVR", "ICICIBANK", "ICICIGI",
    "ICICIPRULI", "INDHOTEL", "INDUSINDBK", "INFY", "IOC",
    "IRCTC", "ITC", "JINDALSTEL", "JSWSTEEL", "KOTAKBANK",
    "LT", "LICI", "LTTS", "LUPIN",
    "M&M", "MANKIND", "MARICO", "MARUTI", "MOTHERSON",
    "MUTHOOTFIN", "NESTLEIND", "NHPC", "NTPC", "ONGC",
    "PAGEIND", "POONAWALLA", "PERSISTENT", "PIDILITIND", "PNB",
    "POLICYBZR", "POWERGRID", "RECLTD", "RELIANCE", "SBICARD",
    "SBILIFE", "SBIN", "SHREECEM", "SHRIRAMFIN", "SIEMENS",
    "SUNPHARMA", "SUPREMEIND", "TATACHEM", "TATACOMM", "TATACONSUM",
    "TMCV", "TATAPOWER", "TATASTEEL", "TCS", "TECHM",
    "TITAN", "TORNTPHARM", "TRENT", "ULTRACEMCO", "UNIONBANK",
    "UNITDSPR", "UPL", "VBL", "VEDL", "WIPRO",
    "ZYDUSLIFE",
]
