"""Email alerts for bargain stocks via Gmail SMTP."""

import os
import json
import smtplib
from datetime import datetime
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from config import (
    SMTP_SERVER, SMTP_PORT, EMAIL_FROM, EMAIL_APP_PASSWORD,
    EMAIL_TO, DATA_DIR,
)
from shared.utils import logger

ALERTED_FILE = os.path.join(DATA_DIR, "alerted.json")


def load_alerted():
    """Load previously alerted tickers and their prices."""
    if not os.path.exists(ALERTED_FILE):
        return {}
    with open(ALERTED_FILE, "r") as f:
        return json.load(f)


def save_alerted(alerted):
    """Save alerted state."""
    with open(ALERTED_FILE, "w") as f:
        json.dump(alerted, f, indent=2)


def should_alert(ticker, cmp, alerted):
    """Only re-alert if price dropped another 10% since last alert."""
    if ticker not in alerted:
        return True
    last_price = alerted[ticker].get("cmp", 0)
    if last_price <= 0:
        return True
    return cmp < last_price * 0.90


def send_batch_alert(bargains):
    """Send a single email with all bargain stocks found in this cycle."""
    if not EMAIL_FROM or not EMAIL_APP_PASSWORD:
        logger.warning(
            "Email not configured. Set STOCK_MONITOR_EMAIL_FROM and "
            "STOCK_MONITOR_EMAIL_PWD environment variables."
        )
        _log_bargains_to_file(bargains)
        return

    alerted = load_alerted()

    to_alert = []
    for ticker, data, summary in bargains:
        if should_alert(ticker, summary.cmp, alerted):
            to_alert.append((ticker, data, summary))

    if not to_alert:
        logger.info("All bargains already alerted, skipping email.")
        return

    subject = f"Stock Monitor: {len(to_alert)} Bargain(s) Found \u2014 {datetime.now().strftime('%d %b %Y')}"

    html_parts = [
        "<html><body>",
        "<h2>Bargain Stocks Identified</h2>",
        f"<p>Scan completed at {datetime.now().strftime('%Y-%m-%d %H:%M IST')}</p>",
        "<table border='1' cellpadding='8' cellspacing='0' style='border-collapse:collapse;font-family:Arial;'>",
        "<tr style='background:#4472C4;color:white;'>",
        "<th>Ticker</th><th>Company</th><th>CMP</th><th>Intrinsic Value</th>",
        "<th>Upside</th><th>Methods Agree</th><th>Screener Link</th></tr>",
    ]

    for ticker, data, summary in to_alert:
        name = data.get("name", ticker)
        cmp = summary.cmp
        iv = summary.median_iv or 0
        upside = summary.upside_pct or 0
        link = f"https://www.screener.in/company/{ticker}/consolidated/"

        html_parts.append(
            f"<tr style='background:#C6EFCE;'>"
            f"<td><b>{ticker}</b></td>"
            f"<td>{name}</td>"
            f"<td>\u20b9{cmp:,.2f}</td>"
            f"<td>\u20b9{iv:,.2f}</td>"
            f"<td style='color:green;font-weight:bold;'>{upside*100:+.1f}%</td>"
            f"<td>{summary.methods_above_cmp}/10</td>"
            f"<td><a href='{link}'>View</a></td>"
            f"</tr>"
        )

        valid_methods = [r for r in summary.results if r.intrinsic_value and r.intrinsic_value > 0]
        valid_methods.sort(key=lambda r: r.intrinsic_value, reverse=True)
        method_text = "<br>".join(
            f"\u2022 {r.method}: \u20b9{r.intrinsic_value:,.2f} ({r.notes})"
            for r in valid_methods[:3]
        )
        html_parts.append(
            f"<tr><td colspan='7' style='font-size:12px;color:#555;'>"
            f"Top methods: {method_text}</td></tr>"
        )

    html_parts.append("</table>")
    html_parts.append("<br><p style='color:#888;font-size:11px;'>")
    html_parts.append("Generated by Stock Monitor | Not financial advice | Do your own research")
    html_parts.append("</p></body></html>")

    html_body = "\n".join(html_parts)

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = EMAIL_FROM
    msg["To"] = EMAIL_TO
    msg.attach(MIMEText(html_body, "html"))

    try:
        with smtplib.SMTP(SMTP_SERVER, SMTP_PORT) as server:
            server.starttls()
            server.login(EMAIL_FROM, EMAIL_APP_PASSWORD)
            server.sendmail(EMAIL_FROM, EMAIL_TO, msg.as_string())
        logger.info(f"Bargain alert email sent with {len(to_alert)} stocks")

        for ticker, data, summary in to_alert:
            alerted[ticker] = {
                "cmp": summary.cmp,
                "median_iv": summary.median_iv,
                "date": datetime.now().isoformat(),
            }
        save_alerted(alerted)

    except Exception as e:
        logger.error(f"Failed to send email: {e}")
        _log_bargains_to_file(bargains)


def _log_bargains_to_file(bargains):
    """Fallback: log bargains to a text file when email is not configured."""
    filepath = os.path.join(DATA_DIR, "bargains_log.txt")
    with open(filepath, "a", encoding="utf-8") as f:
        f.write(f"\n{'='*60}\n")
        f.write(f"Bargains found at {datetime.now().strftime('%Y-%m-%d %H:%M')}\n")
        f.write(f"{'='*60}\n")
        for ticker, data, summary in bargains:
            f.write(f"{ticker} | CMP: \u20b9{summary.cmp:,.2f} | IV: \u20b9{summary.median_iv:,.2f} | "
                    f"Upside: {summary.upside_pct*100:+.1f}% | {summary.verdict}\n")
    logger.info(f"Bargains logged to {filepath} (email not configured)")
